"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const client = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider client={client}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white `}
        >
          <nav className="bg-white py-4">
            <ul className="flex justify-center">
              <li>
                <Link
                  href="/"
                  className="text-gray-700 text-lg font-medium hover:text-purple-600 transition-colors"
                >
                  Home
                </Link>
              </li>
            </ul>
          </nav>

          {children}
        </body>
      </QueryClientProvider>
    </html>
  );
}
