"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Link from "next/link";
import { Suspense } from "react";
import { Loader } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const client = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<Loader className="animate-spin" size={40}></Loader>}>
      <html lang="en">
        <QueryClientProvider client={client}>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white `}
          >
            <nav className="bg-white py-4">
              <ul className="flex justify-center">
                <li>
                  <Link
                    href="/"
                    className="text-gray-700 text-lg font-medium hover:text-purple-600 transition-colors"
                  >
                    Home
                  </Link>
                </li>
              </ul>
            </nav>

            {children}
          </body>
        </QueryClientProvider>
      </html>
    </Suspense>
  );
}
